export const CheckoutErrorCode = Object.freeze({
  SDK_LOAD_FAILED: 'SDK_LOAD_FAILED',
  SDK_NOT_AVAILABLE: 'SDK_NOT_AVAILABLE',
  SDK_RENDER_FAILED: 'SDK_RENDER_FAILED',
  ORDER_CREATION_FAILED: 'ORDER_CREATION_FAILED',
  CAPTURE_FAILED: 'CAPTURE_FAILED',
  NETWORK_ERROR: 'NETWORK_ERROR',
  SESSION_INVALID: 'SESSION_INVALID',
  PAYPAL_CANCELLED: 'PAYPAL_CANCELLED',
  PAYPAL_ERROR: 'PAYPAL_ERROR',
} as const);

export type CheckoutErrorCodeType = typeof CheckoutErrorCode[keyof typeof CheckoutErrorCode];